// Deepseek
models = {
  object: 'list',
  data: [
    {
      id: 'deepseek-v4-flash',
      object: 'model',
      owned_by: 'deepseek',
    },
    {
      id: 'deepseek-v4-pro',
      object: 'model',
      owned_by: 'deepseek',
    },
  ],
}

// Kimi en
models = {
  object: 'list',
  data: [
    {
      created: 1781516712,
      id: 'kimi-k2.7-code-highspeed',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      supports_video_in: true,
      supports_reasoning: true,
      context_length: 262144,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-128k-vision-preview',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      context_length: 131072,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-32k',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      context_length: 32768,
    },
    {
      created: 1781516712,
      id: 'kimi-k2.7-code',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      supports_video_in: true,
      supports_reasoning: true,
      context_length: 262144,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-128k',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      context_length: 131072,
    },
    {
      created: 1781516712,
      id: 'kimi-k2.6',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      supports_video_in: true,
      supports_reasoning: true,
      context_length: 262144,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-8k',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      context_length: 8192,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-8k-vision-preview',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      context_length: 8192,
    },
    {
      created: 1781516712,
      id: 'kimi-k2.5',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      supports_video_in: true,
      supports_reasoning: true,
      context_length: 262144,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-auto',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      context_length: 131072,
    },
    {
      created: 1781516712,
      id: 'moonshot-v1-32k-vision-preview',
      object: 'model',
      owned_by: 'moonshot',
      permission: [
        {
          created: 0,
          id: '',
          object: '',
          organization: 'moonshot',
          group: 'moonshot',
          is_blocking: false,
        },
      ],
      root: '',
      parent: '',
      supports_image_in: true,
      context_length: 32768,
    },
  ],
}

// Minimax
// OpenAI API https://api.minimaxi.com/v1/models
models = {
  object: 'list',
  data: [
    { id: 'MiniMax-M3', object: 'model', created: 1780272000, owned_by: 'minimax' },
    { id: 'MiniMax-M2.7', object: 'model', created: 1773799200, owned_by: 'minimax' },
    { id: 'MiniMax-M2.7-highspeed', object: 'model', created: 1773799200, owned_by: 'minimax' },
    { id: 'MiniMax-M2.5', object: 'model', created: 1770948000, owned_by: 'minimax' },
    { id: 'MiniMax-M2.5-highspeed', object: 'model', created: 1770948000, owned_by: 'minimax' },
    { id: 'MiniMax-M2.1', object: 'model', created: 1766455200, owned_by: 'minimax' },
    { id: 'MiniMax-M2.1-highspeed', object: 'model', created: 1766455200, owned_by: 'minimax' },
    { id: 'MiniMax-M2', object: 'model', created: 1761530400, owned_by: 'minimax' },
  ],
}
// Anthropic API https://api.minimaxi.com/anthropic/v1/models
models = {
  data: [
    {
      id: 'MiniMax-M3',
      type: 'model',
      display_name: 'MiniMax-M3',
      created_at: '2026-06-01T00:00:00Z',
    },
    {
      id: 'MiniMax-M2.7',
      type: 'model',
      display_name: 'MiniMax-M2.7',
      created_at: '2026-03-18T02:00:00Z',
    },
    {
      id: 'MiniMax-M2.7-highspeed',
      type: 'model',
      display_name: 'MiniMax-M2.7-Highspeed',
      created_at: '2026-03-18T02:00:00Z',
    },
    {
      id: 'MiniMax-M2.5',
      type: 'model',
      display_name: 'MiniMax-M2.5',
      created_at: '2026-02-13T02:00:00Z',
    },
    {
      id: 'MiniMax-M2.5-highspeed',
      type: 'model',
      display_name: 'MiniMax-M2.5-Highspeed',
      created_at: '2026-02-13T02:00:00Z',
    },
    {
      id: 'MiniMax-M2.1',
      type: 'model',
      display_name: 'MiniMax-M2.1',
      created_at: '2025-12-23T02:00:00Z',
    },
    {
      id: 'MiniMax-M2.1-highspeed',
      type: 'model',
      display_name: 'MiniMax-M2.1-Highspeed',
      created_at: '2025-12-23T02:00:00Z',
    },
    {
      id: 'MiniMax-M2',
      type: 'model',
      display_name: 'MiniMax-M2',
      created_at: '2025-10-27T02:00:00Z',
    },
  ],
  first_id: 'MiniMax-M3',
  last_id: 'MiniMax-M2',
  has_more: false,
}
